apiVersion: v1
kind: Service
metadata:
  name: multichainclient-nodeport
  namespace: multichainclient-ns
spec:
  type: NodePort
  selector:
    app: multichainclient
  ports:
    - port: 9081
      targetPort: 9081
      nodePort: 31081
---
apiVersion: apps/v1  #Deployment and StatefulSet is defined in apps/v1 not in corev1
kind: Deployment
metadata:
  name: multichainclient   #name of the deployment
  namespace: multichainclient-ns
  labels:
    app: multichainclient
spec:
  replicas: 1  #for testing purpose i set to 1
  selector:
    matchLabels:
      app: multichainclient
  template:
    metadata:
      labels:
        app: multichainclient
    spec:
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 10    #当删除Pod时，等待时间
      containers:
        - name: multichainclient
          image: 127.0.0.1:5000/multichain-client:1.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: port
              containerPort: 9081
          volumeMounts:
            - mountPath: /logs  #directory in docker container
              name: log
          env:
            - name: APP_NAME
              value: "multichainclient-server"  #the service name registered in eureka
            - name: server.port
              value: "9081"
          resources:
            requests:
              memory: "300Mi"
              cpu: "300m"
            limits:
              memory: "300Mi"
              cpu: "300m"
      volumes:
        - name: log
          hostPath:
            path: /home/multichainclient-service-k8s/logs  # directory location on host
            type: DirectoryOrCreate